image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      nix-shell &&
      de-preload
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addBadge: true
    addLabel: true
    
vscode:
  extensions:
    - bbenoist.Nix
    - EditorConfig.EditorConfig
    - Equinusocio.vsc-material-theme
    - PKief.material-icon-theme
    - CoenraadS.bracket-pair-colorizer
    - redhat.vscode-yaml
    - streetsidesoftware.code-spell-checker
    - timonwong.shellcheck